function y = FEMBaseFunRef(type,x1,x2,x3,index,dx,dy,dz)
%FEMBASEFUNREF 参考单元[-1,1]^3上的有限元基函数
%   type：基函数类型
%   x:要计算的点，为一个n*3的矩阵，每一行对应一个点的坐标
%   index：对应的基函数编号
%   dx,dy,dz：分别为对应于x,y,z的导数阶
switch type
    case "linear"
        cube=[1,1,1;...
            1,2,1;...
            2,1,1;...
            2,2,1;...
            1,1,2;...
            1,2,2;...
            2,1,2;...
            2,2,2]; % 每个点处基函数各维度的一维索引
        PHI={@(z) (1-z)/2, @(z) (1+z)/2};
        DPHI={@(z) (-1/2)*ones(length(z),1),@(z) (1/2)*ones(length(z),1)};
    case "quadratic"
        cube =[1,1,1;...
            1,2,1;...
            2,1,1;...
            2,2,1;...
            1,1,2;...
            1,2,2;...
            2,1,2;...
            2,2,2;...
            3,1,1;...
            3,2,1;...
            3,1,2;...
            3,2,2;...
            1,3,1;...
            2,3,1;...
            1,3,2;...
            2,3,2;...
            1,1,3;...
            2,1,3;...
            1,2,3;...
            2,2,3;...
            3,1,3;...
            3,2,3;...
            1,3,3;...
            2,3,3;...
            3,3,1;...
            3,3,2;...
            3,3,3];%参考单元节点与基函数对应关系
        PHI={@(z)z.*(z-1)/2,@(z)z.*(z+1)/2,@(z)(1-z.^2)};
        DPHI={@(z) z-0.5,@(z) z+0.5,@(z) -2*z};
end
switch dx
    case 0
        f1=cell2mat(PHI(cube(index,1)));
    case 1
        f1=cell2mat(DPHI(cube(index,1)));
end
switch dy
    case 0
        f2=cell2mat(PHI(cube(index,2)));
    case 1
        f2=cell2mat(DPHI(cube(index,2)));
end
switch dz
    case 0
        f3=cell2mat(PHI(cube(index,3)));
    case 1
        f3=cell2mat(DPHI(cube(index,3)));
end
y=f1(x1).*f2(x2).*f3(x3);
end

